# Generated by Django 4.2.7 on 2026-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('minutes_studied', models.PositiveIntegerField(default=0, verbose_name='minutes studied')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='words learned')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='lessons completed')),
                ('quizzes_taken', models.PositiveIntegerField(default=0, verbose_name='quizzes taken')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP earned')),
            ],
            options={
                'verbose_name': 'daily activity',
                'verbose_name_plural': 'daily activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20, verbose_name='enrollment status')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='progress percentage')),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='total time spent (minutes)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='last activity at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('completed_lessons', models.ManyToManyField(blank=True, related_name='completed_by', to='courses.lesson', verbose_name='completed lessons')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'user progress',
                'verbose_name_plural': 'user progresses',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
