# Generated by Django 4.2.7 on 2026-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='thumbnail')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='difficulty')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='total lessons')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='estimated hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('quiz', 'Quiz'), ('practice', 'Practice')], default='reading', max_length=20, verbose_name='lesson type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='duration (minutes)')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='video URL')),
                ('is_free', models.BooleanField(default=False, verbose_name='is free')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['course', 'order'],
            },
        ),
    ]
