# Generated by Django 4.2.7 on 2026-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_in_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('listening', 'Listening')], default='multiple_choice', max_length=20, verbose_name='question type')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='correct answer')),
                ('options', models.JSONField(default=list, help_text='List of answer options for multiple choice', verbose_name='options')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('quiz_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_in_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('listening', 'Listening')], default='multiple_choice', max_length=20, verbose_name='quiz type')),
                ('time_limit', models.PositiveIntegerField(default=300, help_text='Time limit in seconds, 0 for unlimited', verbose_name='time limit (seconds)')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='passing score (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='total questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='correct answers')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='time taken (seconds)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20, verbose_name='status')),
                ('answers', models.JSONField(default=dict, help_text='Dictionary of question_id: user_answer', verbose_name='answers')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'quiz attempt',
                'verbose_name_plural': 'quiz attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
