# Generated by Django 4.2.7 on 2026-05-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='word')),
                ('phonetic', models.CharField(blank=True, default='', max_length=100, verbose_name='phonetic transcription')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default='noun', max_length=20, verbose_name='part of speech')),
                ('definition', models.TextField(verbose_name='definition')),
                ('example_sentence', models.TextField(blank=True, default='', verbose_name='example sentence')),
                ('example_sentence_vi', models.TextField(blank=True, default='', verbose_name='example sentence (Vietnamese)')),
                ('definition_vi', models.TextField(blank=True, default='', verbose_name='definition (Vietnamese)')),
                ('synonym', models.CharField(blank=True, default='', max_length=500, verbose_name='synonyms')),
                ('antonym', models.CharField(blank=True, default='', max_length=500, verbose_name='antonyms')),
                ('difficulty', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20, verbose_name='difficulty')),
                ('image', models.ImageField(blank=True, null=True, upload_to='words/images/', verbose_name='image')),
                ('audio_url', models.URLField(blank=True, default='', verbose_name='audio URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False, verbose_name='is learned')),
                ('review_status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=20, verbose_name='review status')),
                ('times_reviewed', models.PositiveIntegerField(default=0, verbose_name='times reviewed')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='correct count')),
                ('incorrect_count', models.PositiveIntegerField(default=0, verbose_name='incorrect count')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='last reviewed at')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='next review at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='vocabulary.word', verbose_name='word')),
            ],
            options={
                'verbose_name': 'user word',
                'verbose_name_plural': 'user words',
                'ordering': ['-last_reviewed_at'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
