"""
Seed data: 3 sample courses with 5 lessons each.
"""

SEED_COURSES = [
    {
        "title": "English for Beginners",
        "slug": "english-for-beginners",
        "description": "A comprehensive course for absolute beginners. Learn basic English grammar, vocabulary, and conversational skills to build a strong foundation.",
        "difficulty": "beginner",
        "estimated_hours": 10.0,
        "lessons": [
            {
                "title": "Greetings and Introductions",
                "slug": "greetings-and-introductions",
                "content": "<h2>Lesson 1: Greetings and Introductions</h2><p>In this lesson, you will learn how to greet people and introduce yourself in English.</p><h3>Common Greetings</h3><ul><li>Hello / Hi - Xin chào</li><li>Good morning - Chào buổi sáng</li><li>Good afternoon - Chào buổi chiều</li><li>Good evening - Chào buổi tối</li><li>How are you? - Bạn khỏe không?</li><li>Nice to meet you - Rất vui được gặp bạn</li></ul><h3>Self Introduction</h3><p>My name is [name]. I am from [country]. I am [age] years old. I work as a [job]. I like [hobby].</p><h3>Practice</h3><p>Try introducing yourself using the template above. Practice saying it out loud several times.</p>",
                "lesson_type": "reading",
                "order": 1,
                "duration_minutes": 20,
                "is_free": True,
            },
            {
                "title": "Numbers and Counting",
                "slug": "numbers-and-counting",
                "content": "<h2>Lesson 2: Numbers and Counting</h2><p>Learn to count from 1 to 100 and use numbers in daily life.</p><h3>Numbers 1-20</h3><p>one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty</p><h3>Tens</h3><p>thirty (30), forty (40), fifty (50), sixty (60), seventy (70), eighty (80), ninety (90), one hundred (100)</p><h3>Using Numbers</h3><ul><li>I have three brothers. - Tôi có ba anh em.</li><li>The meeting is at 2 o'clock. - Cuộc họp lúc 2 giờ.</li><li>There are 25 students in the class. - Có 25 học sinh trong lớp.</li></ul>",
                "lesson_type": "reading",
                "order": 2,
                "duration_minutes": 15,
                "is_free": True,
            },
            {
                "title": "Basic Sentence Structure",
                "slug": "basic-sentence-structure",
                "content": "<h2>Lesson 3: Basic Sentence Structure</h2><p>English sentences follow the Subject-Verb-Object (SVO) pattern.</p><h3>Simple Sentences</h3><ul><li>Subject + Verb: She reads. (Cô ấy đọc.)</li><li>Subject + Verb + Object: I eat rice. (Tôi ăn cơm.)</li><li>Subject + Verb + Adjective: He is happy. (Anh ấy vui.)</li></ul><h3>Present Simple Tense</h3><p>Use for habits and facts:</p><ul><li>I study English every day.</li><li>The sun rises in the east.</li><li>She works at a hospital.</li></ul><h3>Negative Sentences</h3><p>Add 'do not' or 'does not':</p><ul><li>I do not like coffee.</li><li>She does not speak French.</li></ul>",
                "lesson_type": "reading",
                "order": 3,
                "duration_minutes": 25,
                "is_free": False,
            },
            {
                "title": "Common Phrases for Daily Life",
                "slug": "common-phrases-daily-life",
                "content": "<h2>Lesson 4: Common Phrases for Daily Life</h2><p>Essential phrases you'll use every day.</p><h3>At the Store</h3><ul><li>How much is this? - Cái này bao nhiêu?</li><li>Can I pay by card? - Tôi trả bằng thẻ được không?</li><li>I'm just looking. - Tôi chỉ xem thôi.</li></ul><h3>Asking for Help</h3><ul><li>Excuse me, can you help me? - Xin lỗi, bạn giúp tôi được không?</li><li>Where is the bathroom? - Nhà vệ sinh ở đâu?</li><li>Can you speak slowly? - Bạn nói chậm lại được không?</li></ul><h3>At a Restaurant</h3><ul><li>Can I see the menu? - Cho tôi xem thực đơn được không?</li><li>I'd like to order... - Tôi muốn gọi...</li><li>The bill, please. - Cho tôi xin hóa đơn.</li></ul>",
                "lesson_type": "practice",
                "order": 4,
                "duration_minutes": 20,
                "is_free": False,
            },
            {
                "title": "Beginner Assessment Quiz",
                "slug": "beginner-assessment-quiz",
                "content": "<h2>Lesson 5: Beginner Assessment Quiz</h2><p>Test your knowledge from all previous lessons. This quiz covers greetings, numbers, sentence structure, and common phrases.</p><p>Complete all 10 questions to earn your beginner certificate!</p>",
                "lesson_type": "quiz",
                "order": 5,
                "duration_minutes": 15,
                "is_free": False,
            },
        ],
    },
    {
        "title": "Business English Essentials",
        "slug": "business-english-essentials",
        "description": "Master professional English for the workplace. Learn email writing, meeting participation, presentations, and business negotiations.",
        "difficulty": "intermediate",
        "estimated_hours": 15.0,
        "lessons": [
            {
                "title": "Professional Email Writing",
                "slug": "professional-email-writing",
                "content": "<h2>Lesson 1: Professional Email Writing</h2><p>Learn to write clear, professional emails in English.</p><h3>Email Structure</h3><ol><li><strong>Subject Line:</strong> Be specific and concise</li><li><strong>Salutation:</strong> Dear Mr./Ms. [Name],</li><li><strong>Opening:</strong> I hope this email finds you well.</li><li><strong>Body:</strong> State your purpose clearly</li><li><strong>Closing:</strong> Best regards, / Kind regards,</li></ol><h3>Useful Phrases</h3><ul><li>I am writing to inquire about... - Tôi viết để hỏi về...</li><li>Please find attached... - Vui lòng xem file đính kèm...</li><li>I look forward to hearing from you. - Tôi mong nhận được phản hồi.</li><li>Thank you for your prompt response. - Cảm ơn phản hồi nhanh chóng.</li></ul>",
                "lesson_type": "reading",
                "order": 1,
                "duration_minutes": 30,
                "is_free": True,
            },
            {
                "title": "Meeting Participation",
                "slug": "meeting-participation",
                "content": "<h2>Lesson 2: Meeting Participation</h2><p>Essential phrases and skills for participating in business meetings.</p><h3>Starting a Meeting</h3><ul><li>Let's get started. - Hãy bắt đầu.</li><li>The purpose of today's meeting is... - Mục đích cuộc họp hôm nay là...</li></ul><h3>Expressing Opinions</h3><ul><li>In my opinion... - Theo ý kiến của tôi...</li><li>I believe that... - Tôi tin rằng...</li><li>From my perspective... - Từ góc nhìn của tôi...</li></ul><h3>Agreeing and Disagreeing</h3><ul><li>I agree with... - Tôi đồng ý với...</li><li>I see your point, but... - Tôi hiểu ý bạn, nhưng...</li><li>I'm afraid I disagree. - Tôi e là không đồng ý.</li></ul>",
                "lesson_type": "practice",
                "order": 2,
                "duration_minutes": 25,
                "is_free": False,
            },
            {
                "title": "Presentation Skills",
                "slug": "presentation-skills",
                "content": "<h2>Lesson 3: Presentation Skills</h2><p>How to deliver effective presentations in English.</p><h3>Opening Your Presentation</h3><ul><li>Good morning, everyone. Thank you for being here.</li><li>Today, I'd like to talk about...</li><li>The topic of my presentation is...</li></ul><h3>Structuring Content</h3><p>Use signpost language:</p><ul><li>First of all... / Firstly... - Trước hết...</li><li>Moving on to... - Chuyển sang...</li><li>In conclusion... - Kết luận...</li></ul><h3>Handling Questions</h3><ul><li>That's a great question. - Đó là câu hỏi hay.</li><li>Let me clarify that point. - Để tôi làm rõ điểm đó.</li><li>I'll address that later. - Tôi sẽ đề cập sau.</li></ul>",
                "lesson_type": "reading",
                "order": 3,
                "duration_minutes": 30,
                "is_free": False,
            },
            {
                "title": "Negotiation Language",
                "slug": "negotiation-language",
                "content": "<h2>Lesson 4: Negotiation Language</h2><p>Key phrases for successful business negotiations.</p><h3>Making Proposals</h3><ul><li>We'd like to propose... - Chúng tôi muốn đề xuất...</li><li>What if we... - Nếu chúng ta... thì sao?</li><li>Would you consider...? - Bạn có cân nhắc...?</li></ul><h3>Counter-offers</h3><ul><li>We can offer... but we need... - Chúng tôi có thể đưa ra... nhưng cần...</li><li>That's beyond our budget. - Điều đó vượt ngân sách.</li><li>Can we meet halfway? - Chúng ta gặp nhau ở giữa được không?</li></ul><h3>Closing a Deal</h3><ul><li>I think we have a deal. - Tôi nghĩ chúng ta đã thỏa thuận.</li><li>Let's put this in writing. - Hãy ghi lại bằng văn bản.</li></ul>",
                "lesson_type": "practice",
                "order": 4,
                "duration_minutes": 25,
                "is_free": False,
            },
            {
                "title": "Business English Assessment",
                "slug": "business-english-assessment",
                "content": "<h2>Lesson 5: Business English Assessment</h2><p>Comprehensive assessment covering all business English topics.</p><p>This assessment includes email writing exercises, meeting scenarios, and negotiation role-plays.</p>",
                "lesson_type": "quiz",
                "order": 5,
                "duration_minutes": 20,
                "is_free": False,
            },
        ],
    },
    {
        "title": "Advanced English Mastery",
        "slug": "advanced-english-mastery",
        "description": "Take your English to the next level. Master complex grammar, idiomatic expressions, academic writing, and advanced vocabulary for professional and academic contexts.",
        "difficulty": "advanced",
        "estimated_hours": 20.0,
        "lessons": [
            {
                "title": "Advanced Grammar Structures",
                "slug": "advanced-grammar-structures",
                "content": "<h2>Lesson 1: Advanced Grammar Structures</h2><p>Master complex grammar patterns used in academic and professional English.</p><h3>Conditional Sentences</h3><p><strong>Mixed Conditionals:</strong></p><ul><li>If I had studied harder, I would have a better job now.</li><li>If she were more experienced, she would have gotten the promotion.</li></ul><h3>Inversion</h3><ul><li>Not only did he pass, but he also got the highest score.</li><li>Never have I seen such a beautiful sunset.</li><li>Had I known, I would have acted differently.</li></ul><h3>Subjunctive Mood</h3><ul><li>I suggest that he be present at the meeting.</li><li>It is essential that she arrive on time.</li></ul>",
                "lesson_type": "reading",
                "order": 1,
                "duration_minutes": 35,
                "is_free": True,
            },
            {
                "title": "Idiomatic Expressions",
                "slug": "idiomatic-expressions",
                "content": "<h2>Lesson 2: Idiomatic Expressions</h2><p>Common English idioms used by native speakers.</p><h3>Business Idioms</h3><ul><li><strong>Think outside the box</strong> - Think creatively (Suy nghĩ sáng tạo)</li><li><strong>Get the ball rolling</strong> - Start something (Bắt đầu)</li><li><strong>Hit the nail on the head</strong> - Be exactly right (Nói đúng trọng tâm)</li><li><strong>Bite the bullet</strong> - Face a difficult situation (Đối mặt khó khăn)</li><li><strong>Cut corners</strong> - Do something cheaply/poorly (Làm qua loa)</li></ul><h3>Everyday Idioms</h3><ul><li><strong>Piece of cake</strong> - Very easy (Rất dễ)</li><li><strong>Break a leg</strong> - Good luck (Chúc may mắn)</li><li><strong>Under the weather</strong> - Feeling sick (Cảm thấy không khỏe)</li></ul>",
                "lesson_type": "reading",
                "order": 2,
                "duration_minutes": 30,
                "is_free": False,
            },
            {
                "title": "Academic Writing",
                "slug": "academic-writing",
                "content": "<h2>Lesson 3: Academic Writing</h2><p>Principles of effective academic writing in English.</p><h3>Essay Structure</h3><ol><li><strong>Introduction:</strong> Hook, background, thesis statement</li><li><strong>Body Paragraphs:</strong> Topic sentence, evidence, analysis</li><li><strong>Conclusion:</strong> Restate thesis, summarize, final thought</li></ol><h3>Academic Vocabulary</h3><ul><li>Furthermore / Moreover - Hơn nữa</li><li>Nevertheless / Nonetheless - Tuy nhiên</li><li>Consequently / Therefore - Do đó</li><li>In contrast / Conversely - Ngược lại</li></ul><h3>Avoiding Plagiarism</h3><p>Always cite your sources using APA, MLA, or Chicago style. Paraphrase effectively and use direct quotations appropriately.</p>",
                "lesson_type": "reading",
                "order": 3,
                "duration_minutes": 40,
                "is_free": False,
            },
            {
                "title": "Debate and Discussion",
                "slug": "debate-and-discussion",
                "content": "<h2>Lesson 4: Debate and Discussion</h2><p>Skills for engaging in sophisticated English discussions and debates.</p><h3>Presenting Arguments</h3><ul><li>The evidence suggests that... - Bằng chứng cho thấy...</li><li>It can be argued that... - Có thể lập luận rằng...</li><li>Research indicates... - Nghiên cứu chỉ ra...</li></ul><h3>Counter-Arguments</h3><ul><li>While that may be true, one must consider... - Dù có thể đúng, cần cân nhắc...</li><li>However, this overlooks the fact that... - Tuy nhiên, điều này bỏ qua thực tế...</li><li>The flaw in this argument is... - Lỗi trong lập luận này là...</li></ul><h3>Diplomatic Language</h3><ul><li>I appreciate your point, however... - Tôi trân trọng ý kiến, tuy nhiên...</li><li>With all due respect... - Với tất cả sự tôn trọng...</li></ul>",
                "lesson_type": "practice",
                "order": 4,
                "duration_minutes": 30,
                "is_free": False,
            },
            {
                "title": "Advanced Mastery Exam",
                "slug": "advanced-mastery-exam",
                "content": "<h2>Lesson 5: Advanced Mastery Exam</h2><p>Final comprehensive exam testing all advanced English skills.</p><p>This exam includes advanced grammar, idioms, academic writing, and debate questions. Score 80% or above to earn the Advanced Mastery Certificate.</p>",
                "lesson_type": "quiz",
                "order": 5,
                "duration_minutes": 30,
                "is_free": False,
            },
        ],
    },
]
