"""
Seed data: 50 common English words with definitions and examples.
"""

SEED_WORDS = [
    {
        "word": "abundant",
        "phonetic": "/əˈbʌndənt/",
        "part_of_speech": "adjective",
        "definition": "Existing or available in large quantities; plentiful.",
        "definition_vi": "Dồi dào, phong phú, có sẵn với số lượng lớn.",
        "example_sentence": "The region has abundant natural resources.",
        "example_sentence_vi": "Khu vực này có tài nguyên thiên nhiên dồi dào.",
        "synonym": "plentiful, ample, copious",
        "antonym": "scarce, insufficient",
        "difficulty": "intermediate",
    },
    {
        "word": "achieve",
        "phonetic": "/əˈtʃiːv/",
        "part_of_speech": "verb",
        "definition": "To successfully reach a desired result through effort.",
        "definition_vi": "Đạt được kết quả mong muốn thông qua nỗ lực.",
        "example_sentence": "She achieved her goal of becoming a doctor.",
        "example_sentence_vi": "Cô ấy đã đạt được mục tiêu trở thành bác sĩ.",
        "synonym": "accomplish, attain, realize",
        "antonym": "fail, lose",
        "difficulty": "basic",
    },
    {
        "word": "benevolent",
        "phonetic": "/bəˈnevələnt/",
        "part_of_speech": "adjective",
        "definition": "Well-meaning and kindly; charitable.",
        "definition_vi": "Nhân từ, tốt bụng, hay làm từ thiện.",
        "example_sentence": "The benevolent donor gave millions to charity.",
        "example_sentence_vi": "Nhà hảo tâm nhân từ đã quyên góp hàng triệu cho từ thiện.",
        "synonym": "kind, generous, charitable",
        "antonym": "malevolent, cruel",
        "difficulty": "advanced",
    },
    {
        "word": "communicate",
        "phonetic": "/kəˈmjuːnɪkeɪt/",
        "part_of_speech": "verb",
        "definition": "To share or exchange information, ideas, or feelings.",
        "definition_vi": "Chia sẻ hoặc trao đổi thông tin, ý tưởng hoặc cảm xúc.",
        "example_sentence": "We need to communicate more effectively.",
        "example_sentence_vi": "Chúng ta cần giao tiếp hiệu quả hơn.",
        "synonym": "convey, express, share",
        "antonym": "conceal, hide",
        "difficulty": "basic",
    },
    {
        "word": "diligent",
        "phonetic": "/ˈdɪlɪdʒənt/",
        "part_of_speech": "adjective",
        "definition": "Having or showing care and effort in one's work.",
        "definition_vi": "Chăm chỉ, siêng năng trong công việc.",
        "example_sentence": "She is a diligent student who always completes her homework.",
        "example_sentence_vi": "Cô ấy là một học sinh chăm chỉ luôn hoàn thành bài tập.",
        "synonym": "hardworking, industrious, assiduous",
        "antonym": "lazy, negligent",
        "difficulty": "intermediate",
    },
    {
        "word": "elaborate",
        "phonetic": "/ɪˈlæbərət/",
        "part_of_speech": "adjective",
        "definition": "Involving many carefully arranged parts or details.",
        "definition_vi": "Công phu, tỉ mỉ, có nhiều chi tiết được sắp xếp cẩn thận.",
        "example_sentence": "The architect presented an elaborate design for the building.",
        "example_sentence_vi": "Kiến trúc sư trình bày một thiết kế công phu cho tòa nhà.",
        "synonym": "detailed, intricate, complex",
        "antonym": "simple, basic",
        "difficulty": "intermediate",
    },
    {
        "word": "fluctuate",
        "phonetic": "/ˈflʌktʃueɪt/",
        "part_of_speech": "verb",
        "definition": "To rise and fall irregularly in number or amount.",
        "definition_vi": "Dao động, biến động không đều về số lượng.",
        "example_sentence": "Oil prices fluctuate depending on global demand.",
        "example_sentence_vi": "Giá dầu dao động tùy thuộc vào nhu cầu toàn cầu.",
        "synonym": "vary, oscillate, waver",
        "antonym": "stabilize, remain",
        "difficulty": "advanced",
    },
    {
        "word": "gratitude",
        "phonetic": "/ˈɡrætɪtjuːd/",
        "part_of_speech": "noun",
        "definition": "The quality of being thankful; readiness to show appreciation.",
        "definition_vi": "Lòng biết ơn, sự biết ơn.",
        "example_sentence": "She expressed her gratitude with a heartfelt letter.",
        "example_sentence_vi": "Cô ấy bày tỏ lòng biết ơn bằng một bức thư chân thành.",
        "synonym": "thankfulness, appreciation, gratefulness",
        "antonym": "ingratitude",
        "difficulty": "basic",
    },
    {
        "word": "hesitate",
        "phonetic": "/ˈhezɪteɪt/",
        "part_of_speech": "verb",
        "definition": "To pause before saying or doing something.",
        "definition_vi": "Do dự, ngần ngại trước khi nói hoặc làm điều gì.",
        "example_sentence": "Don't hesitate to ask for help when you need it.",
        "example_sentence_vi": "Đừng ngần ngại yêu cầu giúp đỡ khi bạn cần.",
        "synonym": "pause, waver, falter",
        "antonym": "proceed, decide",
        "difficulty": "basic",
    },
    {
        "word": "implement",
        "phonetic": "/ˈɪmplɪment/",
        "part_of_speech": "verb",
        "definition": "To put a plan or decision into effect.",
        "definition_vi": "Thực hiện, triển khai một kế hoạch hoặc quyết định.",
        "example_sentence": "The company will implement the new policy next month.",
        "example_sentence_vi": "Công ty sẽ triển khai chính sách mới vào tháng tới.",
        "synonym": "execute, carry out, apply",
        "antonym": "abandon, neglect",
        "difficulty": "intermediate",
    },
    {
        "word": "justify",
        "phonetic": "/ˈdʒʌstɪfaɪ/",
        "part_of_speech": "verb",
        "definition": "To show or prove to be right or reasonable.",
        "definition_vi": "Biện minh, chứng minh là đúng hoặc hợp lý.",
        "example_sentence": "How can you justify such expensive spending?",
        "example_sentence_vi": "Làm sao bạn có thể biện minh cho việc chi tiêu đắt đỏ như vậy?",
        "synonym": "defend, explain, rationalize",
        "antonym": "condemn, criticize",
        "difficulty": "intermediate",
    },
    {
        "word": "knowledge",
        "phonetic": "/ˈnɒlɪdʒ/",
        "part_of_speech": "noun",
        "definition": "Facts, information, and skills acquired through experience or education.",
        "definition_vi": "Kiến thức, sự hiểu biết thu được qua kinh nghiệm hoặc giáo dục.",
        "example_sentence": "Her knowledge of history is impressive.",
        "example_sentence_vi": "Kiến thức lịch sử của cô ấy rất ấn tượng.",
        "synonym": "understanding, wisdom, expertise",
        "antonym": "ignorance",
        "difficulty": "basic",
    },
    {
        "word": "leverage",
        "phonetic": "/ˈlevərɪdʒ/",
        "part_of_speech": "verb",
        "definition": "To use something to maximum advantage.",
        "definition_vi": "Tận dụng, sử dụng cái gì đó để đạt lợi thế tối đa.",
        "example_sentence": "We can leverage social media to reach more customers.",
        "example_sentence_vi": "Chúng ta có thể tận dụng mạng xã hội để tiếp cận nhiều khách hàng hơn.",
        "synonym": "utilize, exploit, capitalize on",
        "antonym": "waste, squander",
        "difficulty": "advanced",
    },
    {
        "word": "meticulous",
        "phonetic": "/mɪˈtɪkjələs/",
        "part_of_speech": "adjective",
        "definition": "Showing great attention to detail; very careful.",
        "definition_vi": "Tỉ mỉ, cẩn thận, chú ý đến từng chi tiết.",
        "example_sentence": "She is meticulous about keeping her workspace organized.",
        "example_sentence_vi": "Cô ấy rất tỉ mỉ trong việc giữ nơi làm việc gọn gàng.",
        "synonym": "thorough, precise, scrupulous",
        "antonym": "careless, sloppy",
        "difficulty": "advanced",
    },
    {
        "word": "negotiate",
        "phonetic": "/nɪˈɡəʊʃieɪt/",
        "part_of_speech": "verb",
        "definition": "To discuss something in order to reach an agreement.",
        "definition_vi": "Đàm phán, thương lượng để đạt được thỏa thuận.",
        "example_sentence": "They negotiated a better deal on the contract.",
        "example_sentence_vi": "Họ đã đàm phán được một thỏa thuận tốt hơn trong hợp đồng.",
        "synonym": "bargain, discuss, mediate",
        "antonym": "refuse, reject",
        "difficulty": "intermediate",
    },
    {
        "word": "obstacle",
        "phonetic": "/ˈɒbstəkl/",
        "part_of_speech": "noun",
        "definition": "A thing that blocks one's way or prevents progress.",
        "definition_vi": "Trở ngại, vật cản đường hoặc ngăn cản sự tiến bộ.",
        "example_sentence": "Lack of funding was the main obstacle to the project.",
        "example_sentence_vi": "Thiếu kinh phí là trở ngại chính cho dự án.",
        "synonym": "barrier, hindrance, impediment",
        "antonym": "aid, assistance",
        "difficulty": "basic",
    },
    {
        "word": "persevere",
        "phonetic": "/ˌpɜːsɪˈvɪə/",
        "part_of_speech": "verb",
        "definition": "To continue in a course of action despite difficulty.",
        "definition_vi": "Kiên trì, bền bỉ tiếp tục dù gặp khó khăn.",
        "example_sentence": "She persevered through many challenges to succeed.",
        "example_sentence_vi": "Cô ấy đã kiên trì vượt qua nhiều thách thức để thành công.",
        "synonym": "persist, endure, continue",
        "antonym": "quit, give up",
        "difficulty": "intermediate",
    },
    {
        "word": "resilient",
        "phonetic": "/rɪˈzɪliənt/",
        "part_of_speech": "adjective",
        "definition": "Able to recover quickly from difficult conditions.",
        "definition_vi": "Kiên cường, có khả năng phục hồi nhanh chóng.",
        "example_sentence": "Children are often more resilient than adults think.",
        "example_sentence_vi": "Trẻ em thường kiên cường hơn người lớn nghĩ.",
        "synonym": "tough, strong, adaptable",
        "antonym": "fragile, weak",
        "difficulty": "advanced",
    },
    {
        "word": "substantial",
        "phonetic": "/səbˈstænʃəl/",
        "part_of_speech": "adjective",
        "definition": "Of considerable importance, size, or worth.",
        "definition_vi": "Đáng kể, quan trọng về kích thước hoặc giá trị.",
        "example_sentence": "The company made a substantial profit this year.",
        "example_sentence_vi": "Công ty đã đạt lợi nhuận đáng kể trong năm nay.",
        "synonym": "significant, considerable, large",
        "antonym": "insignificant, trivial",
        "difficulty": "intermediate",
    },
    {
        "word": "transparent",
        "phonetic": "/trænsˈpærənt/",
        "part_of_speech": "adjective",
        "definition": "Easy to perceive or detect; open and honest.",
        "definition_vi": "Minh bạch, dễ nhận biết; cởi mở và trung thực.",
        "example_sentence": "The government promised a transparent decision-making process.",
        "example_sentence_vi": "Chính phủ hứa một quy trình ra quyết định minh bạch.",
        "synonym": "clear, open, honest",
        "antonym": "opaque, secretive",
        "difficulty": "intermediate",
    },
    {
        "word": "ubiquitous",
        "phonetic": "/juːˈbɪkwɪtəs/",
        "part_of_speech": "adjective",
        "definition": "Present, appearing, or found everywhere.",
        "definition_vi": "Có mặt ở khắp mọi nơi, phổ biến.",
        "example_sentence": "Smartphones have become ubiquitous in modern life.",
        "example_sentence_vi": "Điện thoại thông minh đã trở nên phổ biến trong cuộc sống hiện đại.",
        "synonym": "omnipresent, universal, pervasive",
        "antonym": "rare, uncommon",
        "difficulty": "advanced",
    },
    {
        "word": "versatile",
        "phonetic": "/ˈvɜːsətaɪl/",
        "part_of_speech": "adjective",
        "definition": "Able to adapt to many different functions or activities.",
        "definition_vi": "Đa năng, có khả năng thích ứng với nhiều chức năng.",
        "example_sentence": "She is a versatile musician who plays five instruments.",
        "example_sentence_vi": "Cô ấy là một nhạc sĩ đa năng chơi được năm nhạc cụ.",
        "synonym": "adaptable, flexible, multifaceted",
        "antonym": "limited, inflexible",
        "difficulty": "intermediate",
    },
    {
        "word": "whimsical",
        "phonetic": "/ˈwɪmzɪkəl/",
        "part_of_speech": "adjective",
        "definition": "Playfully quaint or fanciful, especially in an appealing way.",
        "definition_vi": "Kỳ quặc một cách vui tươi, hay tưởng tượng.",
        "example_sentence": "The garden had a whimsical design with colorful sculptures.",
        "example_sentence_vi": "Khu vườn có thiết kế kỳ thú với những bức tượng đầy màu sắc.",
        "synonym": "playful, fanciful, quirky",
        "antonym": "serious, practical",
        "difficulty": "advanced",
    },
    {
        "word": "advocate",
        "phonetic": "/ˈædvəkeɪt/",
        "part_of_speech": "verb",
        "definition": "To publicly recommend or support a particular cause or policy.",
        "definition_vi": "Ủng hộ, biện hộ công khai cho một nguyên nhân hoặc chính sách.",
        "example_sentence": "She advocates for environmental protection.",
        "example_sentence_vi": "Cô ấy ủng hộ bảo vệ môi trường.",
        "synonym": "support, champion, promote",
        "antonym": "oppose, criticize",
        "difficulty": "intermediate",
    },
    {
        "word": "brevity",
        "phonetic": "/ˈbrevɪti/",
        "part_of_speech": "noun",
        "definition": "Concise and exact use of words in writing or speech.",
        "definition_vi": "Sự ngắn gọn, súc tích trong văn viết hoặc lời nói.",
        "example_sentence": "The brevity of his speech surprised everyone.",
        "example_sentence_vi": "Sự ngắn gọn trong bài phát biểu của anh ấy làm mọi người ngạc nhiên.",
        "synonym": "conciseness, shortness, succinctness",
        "antonym": "verbosity, wordiness",
        "difficulty": "advanced",
    },
    {
        "word": "collaborate",
        "phonetic": "/kəˈlæbəreɪt/",
        "part_of_speech": "verb",
        "definition": "To work jointly with others on an activity or project.",
        "definition_vi": "Hợp tác, cộng tác với người khác trong một hoạt động.",
        "example_sentence": "The two companies collaborated on the new product.",
        "example_sentence_vi": "Hai công ty đã hợp tác phát triển sản phẩm mới.",
        "synonym": "cooperate, partner, team up",
        "antonym": "compete, oppose",
        "difficulty": "intermediate",
    },
    {
        "word": "determine",
        "phonetic": "/dɪˈtɜːmɪn/",
        "part_of_speech": "verb",
        "definition": "To cause something to occur in a particular way; to decide.",
        "definition_vi": "Quyết định, xác định điều gì đó xảy ra theo cách cụ thể.",
        "example_sentence": "Hard work will determine your success.",
        "example_sentence_vi": "Sự chăm chỉ sẽ quyết định thành công của bạn.",
        "synonym": "decide, establish, ascertain",
        "antonym": "waver, hesitate",
        "difficulty": "basic",
    },
    {
        "word": "empathy",
        "phonetic": "/ˈempəθi/",
        "part_of_speech": "noun",
        "definition": "The ability to understand and share the feelings of another.",
        "definition_vi": "Khả năng thấu hiểu và chia sẻ cảm xúc với người khác.",
        "example_sentence": "Showing empathy is essential in building relationships.",
        "example_sentence_vi": "Thể hiện sự đồng cảm là thiết yếu trong xây dựng mối quan hệ.",
        "synonym": "compassion, understanding, sensitivity",
        "antonym": "apathy, indifference",
        "difficulty": "intermediate",
    },
    {
        "word": "feasible",
        "phonetic": "/ˈfiːzəbl/",
        "part_of_speech": "adjective",
        "definition": "Possible to do easily or conveniently.",
        "definition_vi": "Khả thi, có thể thực hiện dễ dàng.",
        "example_sentence": "Is it feasible to complete the project by Friday?",
        "example_sentence_vi": "Có khả thi để hoàn thành dự án vào thứ Sáu không?",
        "synonym": "possible, viable, practical",
        "antonym": "impossible, impractical",
        "difficulty": "intermediate",
    },
    {
        "word": "genuine",
        "phonetic": "/ˈdʒenjuɪn/",
        "part_of_speech": "adjective",
        "definition": "Truly what something is said to be; authentic and sincere.",
        "definition_vi": "Thật, chân thật, đích thực.",
        "example_sentence": "She showed genuine concern for her friend's wellbeing.",
        "example_sentence_vi": "Cô ấy thể hiện sự quan tâm chân thành đến sức khỏe bạn mình.",
        "synonym": "authentic, real, sincere",
        "antonym": "fake, artificial",
        "difficulty": "basic",
    },
    {
        "word": "innovative",
        "phonetic": "/ˈɪnəveɪtɪv/",
        "part_of_speech": "adjective",
        "definition": "Featuring new methods; advanced and original.",
        "definition_vi": "Đổi mới, sáng tạo, có phương pháp mới.",
        "example_sentence": "The company is known for its innovative products.",
        "example_sentence_vi": "Công ty nổi tiếng với các sản phẩm đổi mới.",
        "synonym": "creative, original, groundbreaking",
        "antonym": "conventional, traditional",
        "difficulty": "intermediate",
    },
    {
        "word": "juxtapose",
        "phonetic": "/ˌdʒʌkstəˈpəʊz/",
        "part_of_speech": "verb",
        "definition": "To place close together for contrasting effect.",
        "definition_vi": "Đặt cạnh nhau để tạo hiệu ứng tương phản.",
        "example_sentence": "The artist juxtaposed light and dark colors.",
        "example_sentence_vi": "Nghệ sĩ đặt các màu sáng và tối cạnh nhau.",
        "synonym": "contrast, compare, place alongside",
        "antonym": "separate, divide",
        "difficulty": "advanced",
    },
    {
        "word": "keen",
        "phonetic": "/kiːn/",
        "part_of_speech": "adjective",
        "definition": "Having or showing eagerness or enthusiasm.",
        "definition_vi": "Hăng hái, nhiệt tình, sắc bén.",
        "example_sentence": "She has a keen interest in learning new languages.",
        "example_sentence_vi": "Cô ấy rất hứng thú với việc học ngôn ngữ mới.",
        "synonym": "eager, enthusiastic, sharp",
        "antonym": "apathetic, dull",
        "difficulty": "basic",
    },
    {
        "word": "lucid",
        "phonetic": "/ˈluːsɪd/",
        "part_of_speech": "adjective",
        "definition": "Expressed clearly; easy to understand.",
        "definition_vi": "Rõ ràng, dễ hiểu, sáng suốt.",
        "example_sentence": "The professor gave a lucid explanation of the theory.",
        "example_sentence_vi": "Giáo sư đưa ra giải thích rõ ràng về lý thuyết.",
        "synonym": "clear, intelligible, coherent",
        "antonym": "confusing, unclear",
        "difficulty": "advanced",
    },
    {
        "word": "mitigate",
        "phonetic": "/ˈmɪtɪɡeɪt/",
        "part_of_speech": "verb",
        "definition": "To make less severe, serious, or painful.",
        "definition_vi": "Giảm nhẹ, làm bớt nghiêm trọng.",
        "example_sentence": "Measures were taken to mitigate the environmental damage.",
        "example_sentence_vi": "Các biện pháp đã được thực hiện để giảm thiệt hại môi trường.",
        "synonym": "alleviate, reduce, diminish",
        "antonym": "aggravate, intensify",
        "difficulty": "advanced",
    },
    {
        "word": "notion",
        "phonetic": "/ˈnəʊʃn/",
        "part_of_speech": "noun",
        "definition": "A conception or belief about something.",
        "definition_vi": "Khái niệm, ý niệm về điều gì đó.",
        "example_sentence": "She had no notion of what would happen next.",
        "example_sentence_vi": "Cô ấy không có ý niệm gì về điều sẽ xảy ra tiếp theo.",
        "synonym": "idea, concept, belief",
        "antonym": "fact, reality",
        "difficulty": "intermediate",
    },
    {
        "word": "optimize",
        "phonetic": "/ˈɒptɪmaɪz/",
        "part_of_speech": "verb",
        "definition": "To make the best or most effective use of something.",
        "definition_vi": "Tối ưu hóa, sử dụng hiệu quả nhất.",
        "example_sentence": "We need to optimize our workflow for better efficiency.",
        "example_sentence_vi": "Chúng ta cần tối ưu hóa quy trình làm việc để hiệu quả hơn.",
        "synonym": "improve, enhance, maximize",
        "antonym": "worsen, degrade",
        "difficulty": "intermediate",
    },
    {
        "word": "paradigm",
        "phonetic": "/ˈpærədaɪm/",
        "part_of_speech": "noun",
        "definition": "A typical example or pattern of something.",
        "definition_vi": "Mô hình, khuôn mẫu điển hình.",
        "example_sentence": "The discovery created a new paradigm in science.",
        "example_sentence_vi": "Khám phá đã tạo ra một mô hình mới trong khoa học.",
        "synonym": "model, pattern, framework",
        "antonym": "anomaly, exception",
        "difficulty": "advanced",
    },
    {
        "word": "reluctant",
        "phonetic": "/rɪˈlʌktənt/",
        "part_of_speech": "adjective",
        "definition": "Unwilling and hesitant; disinclined.",
        "definition_vi": "Miễn cưỡng, không sẵn lòng, do dự.",
        "example_sentence": "He was reluctant to share his opinion.",
        "example_sentence_vi": "Anh ấy miễn cưỡng chia sẻ ý kiến của mình.",
        "synonym": "unwilling, hesitant, disinclined",
        "antonym": "eager, willing",
        "difficulty": "basic",
    },
    {
        "word": "scrutinize",
        "phonetic": "/ˈskruːtɪnaɪz/",
        "part_of_speech": "verb",
        "definition": "To examine or inspect closely and thoroughly.",
        "definition_vi": "Xem xét, kiểm tra kỹ lưỡng và cẩn thận.",
        "example_sentence": "The auditor scrutinized every financial record.",
        "example_sentence_vi": "Kiểm toán viên đã xem xét kỹ từng hồ sơ tài chính.",
        "synonym": "examine, inspect, analyze",
        "antonym": "glance, overlook",
        "difficulty": "advanced",
    },
    {
        "word": "tenacious",
        "phonetic": "/tɪˈneɪʃəs/",
        "part_of_speech": "adjective",
        "definition": "Tending to keep a firm hold; persistent and determined.",
        "definition_vi": "Kiên cường, bền bỉ, quyết tâm.",
        "example_sentence": "Her tenacious spirit helped her overcome all obstacles.",
        "example_sentence_vi": "Tinh thần kiên cường giúp cô vượt qua mọi trở ngại.",
        "synonym": "persistent, determined, stubborn",
        "antonym": "weak, yielding",
        "difficulty": "advanced",
    },
    {
        "word": "unique",
        "phonetic": "/juːˈniːk/",
        "part_of_speech": "adjective",
        "definition": "Being the only one of its kind; unlike anything else.",
        "definition_vi": "Độc đáo, duy nhất, không giống bất kỳ thứ gì khác.",
        "example_sentence": "Each person has a unique fingerprint.",
        "example_sentence_vi": "Mỗi người có một dấu vân tay độc đáo.",
        "synonym": "distinctive, one-of-a-kind, special",
        "antonym": "common, ordinary",
        "difficulty": "basic",
    },
    {
        "word": "vindicate",
        "phonetic": "/ˈvɪndɪkeɪt/",
        "part_of_speech": "verb",
        "definition": "To clear someone of blame or suspicion.",
        "definition_vi": "Minh oan, giải oan, chứng minh vô tội.",
        "example_sentence": "The evidence vindicated the accused man.",
        "example_sentence_vi": "Bằng chứng đã minh oan cho người đàn ông bị buộc tội.",
        "synonym": "exonerate, acquit, absolve",
        "antonym": "accuse, blame",
        "difficulty": "advanced",
    },
    {
        "word": "wary",
        "phonetic": "/ˈweəri/",
        "part_of_speech": "adjective",
        "definition": "Feeling or showing caution about possible dangers.",
        "definition_vi": "Cảnh giác, thận trọng về những nguy hiểm có thể.",
        "example_sentence": "Be wary of strangers offering free gifts.",
        "example_sentence_vi": "Hãy cảnh giác với người lạ tặng quà miễn phí.",
        "synonym": "cautious, careful, vigilant",
        "antonym": "careless, trusting",
        "difficulty": "intermediate",
    },
    {
        "word": "yearn",
        "phonetic": "/jɜːn/",
        "part_of_speech": "verb",
        "definition": "To have an intense feeling of longing for something.",
        "definition_vi": "Khao khát, mong mỏi điều gì đó mãnh liệt.",
        "example_sentence": "She yearned for the days when life was simpler.",
        "example_sentence_vi": "Cô ấy khao khát những ngày cuộc sống đơn giản hơn.",
        "synonym": "long, desire, crave",
        "antonym": "reject, despise",
        "difficulty": "intermediate",
    },
    {
        "word": "zealous",
        "phonetic": "/ˈzeləs/",
        "part_of_speech": "adjective",
        "definition": "Having or showing great energy or enthusiasm.",
        "definition_vi": "Hăng hái, nhiệt tình, sốt sắng.",
        "example_sentence": "The teacher was zealous about promoting reading.",
        "example_sentence_vi": "Giáo viên rất nhiệt tình trong việc thúc đẩy đọc sách.",
        "synonym": "enthusiastic, passionate, fervent",
        "antonym": "apathetic, indifferent",
        "difficulty": "intermediate",
    },
    {
        "word": "aesthetic",
        "phonetic": "/iːsˈθetɪk/",
        "part_of_speech": "adjective",
        "definition": "Concerned with beauty or the appreciation of beauty.",
        "definition_vi": "Thuộc về thẩm mỹ, liên quan đến vẻ đẹp.",
        "example_sentence": "The room has a pleasing aesthetic design.",
        "example_sentence_vi": "Căn phòng có thiết kế thẩm mỹ dễ chịu.",
        "synonym": "artistic, beautiful, tasteful",
        "antonym": "ugly, unattractive",
        "difficulty": "intermediate",
    },
    {
        "word": "comprehensive",
        "phonetic": "/ˌkɒmprɪˈhensɪv/",
        "part_of_speech": "adjective",
        "definition": "Complete; including all or nearly all elements.",
        "definition_vi": "Toàn diện, bao gồm tất cả hoặc gần như tất cả.",
        "example_sentence": "The report provides a comprehensive analysis.",
        "example_sentence_vi": "Báo cáo cung cấp một phân tích toàn diện.",
        "synonym": "thorough, complete, extensive",
        "antonym": "partial, limited",
        "difficulty": "intermediate",
    },
    {
        "word": "endeavor",
        "phonetic": "/ɪnˈdevə/",
        "part_of_speech": "verb",
        "definition": "To try hard to do or achieve something.",
        "definition_vi": "Nỗ lực, cố gắng hết sức để đạt được điều gì.",
        "example_sentence": "We endeavor to provide the best service possible.",
        "example_sentence_vi": "Chúng tôi nỗ lực cung cấp dịch vụ tốt nhất có thể.",
        "synonym": "attempt, strive, try",
        "antonym": "neglect, abandon",
        "difficulty": "intermediate",
    },
    {
        "word": "inevitable",
        "phonetic": "/ɪnˈevɪtəbl/",
        "part_of_speech": "adjective",
        "definition": "Certain to happen; unavoidable.",
        "definition_vi": "Không thể tránh khỏi, chắc chắn xảy ra.",
        "example_sentence": "Change is inevitable in every organization.",
        "example_sentence_vi": "Thay đổi là không thể tránh khỏi trong mọi tổ chức.",
        "synonym": "unavoidable, certain, sure",
        "antonym": "avoidable, uncertain",
        "difficulty": "basic",
    },
]
